[package]
name = "magiclip-dtos"
version = "0.1.0"
authors = ["Walker Crouse <walker.crouse@coop.co.uk>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
